version: '3.5'

services:
  app:
    container_name: odk-app
    build:
      context: ./odk-app
      args:
        - APP_NAME=ODK dev
    ports:
      - "8000:80"

  api:
    container_name: odk-api
    build: ./odk-api
    env_file:
      - ./odk-api/.global.env
      - ./odk-api/.development.env
    ports:
      - "8080:80"

  db:
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=odk
      - POSTGRES_PASSWORD=development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rmq:
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=odk
      - RABBITMQ_DEFAULT_PASS=development
    ports:
       - "8081:8080"
       - "5672:5672"
       - "15672:15672"

volumes:
  postgres-data:
